services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - model_data:/app/data
      - /mnt/c/news-datasets:/data
      - C:/Users/t/Downloads:/app/downloads
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
  jupyter:
    build: ./backend
    ports:
      - "8888:8888"
    volumes:
      - ./backend:/app
      - model_data:/app/data
    command: jupyter notebook --ip=0.0.0.0 --port=8888 --no-browser --allow-root
volumes:
  model_data:
