version: '3.8'

services:
  train_categories_small:
    build: ./backend
    ports:
      - "8888:8888"
    volumes:
      - ./backend:/app
      - model_data:/app/data
    command: python3 train_category_models.py --dataset train --dataset_size small

volumes:
  model_data:
