services:
  model:
    build: ./model
    volumes:
      - ./model:/app
      - model_data:/app/data
      - /mnt/c/news-datasets:/data
    environment:
      - CLEAR_DATASETS=${CLEAR_DATASETS}
    command: bash -c "if [ '$CLEAR_DATASETS' = 'true' ]; then echo "CLEAR_DATASETS=$CLEAR_DATASETS"; rm -rf /data/*; fi && python3 model.py"
  fastformer:
    build: ./Fastformer
    working_dir: /app
    volumes:
      - ./Fastformer:/app
      - model_data:/app/data
      - /mnt/c/news-datasets:/data
    command: "python3 Fastformer.py"
volumes:
  model_data:
