services:
  fastformer:
    build: ./Fastformer
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu, utility, compute]
    working_dir: /app
    ports:
      - "8888:8888"
    volumes:
      - .:/workspace
#      - ./Fastformer:/app
#      - ./model:/model
#      - model_data:/app/data
#      - /mnt/c/news-datasets:/data
    command: jupyter notebook --ip=0.0.0.0 --port=8888 --allow-root --NotebookApp.token='' #cd /app/Fastformer/cuda-samples/Samples/1_Utilities make #python3 /app/Fastformer.py
volumes:
  model_data: