version: '3.3'

services:
  model:
    build: ./model
    volumes:
      - ./model:/app
      - model:/app/data
      - /mnt/c/news-datasets:/data

  backend:
    build: ./backend
    depends_on:
      - model
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - model:/app/data
      - /mnt/c/news-datasets:/data

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
    depends_on:
      - backend
volumes:
  model:
  backend:
  frontend:
